source 'https://github.com/CocoaPods/Specs.git'

#use_frameworks!

platform :ios, '8.0'

target 'DB_Catalog_iOS' do
  pod 'DreamBox_iOS', :git => 'git@git.xiaojukeji.com:DreamBox/dreambox_ios.git'

end
